# Other Groupings

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/dataset.xlsx")
df.head(5)

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Hb saturation (arterial blood gases),pCO2 (arterial blood gas analysis),Base excess (arterial blood gas analysis),pH (arterial blood gas analysis),Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis)
0,44477f75e8169d2,13,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,126e9dd13932f68,17,negative,0,0,0,0.236515,-0.02234,-0.517413,0.010677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a46b4402a0e5696,8,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f7d619a94f97c45,5,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d9e41465789c2b5,15,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
conditions = [
    (df['Patient addmited to regular ward (1=yes, 0=no)'] == 1),
    (df['Patient addmited to semi-intensive unit (1=yes, 0=no)'] == 1),
    (df['Patient addmited to intensive care unit (1=yes, 0=no)'] == 1),
    (df['Patient addmited to intensive care unit (1=yes, 0=no)'] == 0) & 
     (df['Patient addmited to semi-intensive unit (1=yes, 0=no)'] == 0) &
     (df['Patient addmited to regular ward (1=yes, 0=no)'] == 0)]

# create a list of the values we want to assign for each condition
values = ['regular', 'semi', 'icu', 'discharged']

# create a new column and use np.select to assign values to it using our lists as arguments
df['y'] = np.select(conditions, values)

df['y'].value_counts()

discharged    5474
regular         79
semi            50
icu             41
Name: y, dtype: int64

In [21]:
ids = df.loc[:, 'Patient ID':'Patient addmited to intensive care unit (1=yes, 0=no)']
col1 = df.loc[:,'Serum Glucose']
col2 = df.loc[:,'Urea':'Sodium']
col3 = df.loc[:,'Gamma-glutamyltransferase\xa0']
col4 = df.loc[:,'Alkaline phosphatase':'Magnesium']
col5 = df.loc[:,'Partial thromboplastin timeÂ (PTT)Â ':'Ferritin']
col6 = df.loc[:,'Lipase dosage':'Albumin']

other = pd.concat([ids, df['y'], col1, col2, col3, col4, col5, col6], axis=1)

# filter to only positive patients
other = other[other['SARS-Cov-2 exam result'] == 'positive']
other

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",y,Serum Glucose,Urea,Proteina C reativa mg/dL,...,Relationship (Patient/Normal),International normalized ratio (INR),Lactic Dehydrogenase,"Prothrombin time (PT), Activity",Vitamin B12,Creatine phosphokinaseÂ (CPK),Ferritin,Lipase dosage,D-Dimer,Albumin
67,78511c183ae18bc,7,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,d7834ed75f2da44,16,positive,1,0,0,regular,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,b16b49f7bd3e692,10,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,4382f5ea05e60c4,2,positive,0,0,0,discharged,NaN,-0.513909,NaN,...,0.000994,0.86241,-0.620717,NaN,NaN,0.125483,NaN,NaN,NaN,NaN
676,d3729cd2658ca64,15,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5632,5c386388ba3c3f0,16,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5633,9f8dfe2ae239238,4,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5634,db77903261ab6d0,15,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5639,ae66feb9e4dc3a0,3,positive,0,0,0,discharged,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5643,2697fdccbfeb7f7,19,positive,0,0,0,discharged,NaN,0.453725,-0.50357,...,NaN,NaN,0.420204,NaN,NaN,-0.343291,NaN,NaN,NaN,NaN

`Albium`, `D-Dimer`, `Vitamin B12`, `Prothrombin time (PT), Activity` and `Partial thromboplastin time (PTT)` are missing for all covid positive patients so these variables will not be useful at all. In addition, if we use a 98% cut off for removing variables from our analysis, this would also include `Ferritin`, `Lipase dosage`, `Magnesium` and `Ionized calcium`.

Most of the other variables have different amounts of missing values meaning its likely they were not results of any grouping of lab tests done.

In [23]:
other_missing = (other.isnull().sum().sort_values(ascending = False)).to_frame(name = 'num')
other_missing.reset_index(inplace=True)
other_missing.rename(columns = {'index':'var'}, inplace = True)
other_missing['prop'] = other_missing['num']/len(other)
other_missing[other_missing.prop > 0]

                                     var  num      prop
0                                Albumin  558  1.000000
1                                D-Dimer  558  1.000000
2                            Vitamin B12  558  1.000000
3        Prothrombin time (PT), Activity  558  1.000000
4     Partial thromboplastin timeÂ (PTT)Â   558  1.000000
5                               Ferritin  556  0.996416
6                          Lipase dosage  555  0.994624
7                              Magnesium  553  0.991039
8                       Ionized calciumÂ   552  0.989247
9                              Strepto A  544  0.974910
10         Relationship (Patient/Normal)  543  0.973118
11         Creatine phosphokinaseÂ (CPK)Â   535  0.958781
12  International normalized ratio (INR)  535  0.958781
13                  Lactic Dehydrogenase  532  0.953405
14                  Alkaline phosphatase  529  0.948029
15            Gamma-glutamyltransferaseÂ   528  0.946237
16                         Serum Glucose  525  0.940860
17                                Sodium  500  0.896057
18                             Potassium  500  0.896057
19                                  Urea  499  0.894265
20                            Creatinine  496  0.888889
21              Proteina C reativa mg/dL  488  0.874552

In [27]:
other_tests = other.drop(['Patient age quantile',
                    'Patient addmited to regular ward (1=yes, 0=no)',
                   'Patient addmited to semi-intensive unit (1=yes, 0=no)',
                   'Patient addmited to intensive care unit (1=yes, 0=no)',
                   'Albumin', 'D-Dimer', 'Vitamin B12', 
                    'Prothrombin time (PT), Activity', 'Partial thromboplastin timeÂ (PTT)Â ',
                    'Ferritin', 'Lipase dosage', 'Magnesium', 
                          'Ionized calciumÂ '], axis = 1, inplace = False)
other_tests.groupby('y').mean()

,Serum Glucose,Urea,Proteina C reativa mg/dL,Creatinine,Potassium,Sodium,Gamma-glutamyltransferase,Alkaline phosphatase,Relationship (Patient/Normal),International normalized ratio (INR),Lactic Dehydrogenase,Creatine phosphokinaseÂ (CPK)
y,,,,,,,,,,,,
discharged,0.016281,-0.290609,-0.261949,-0.096908,0.008782,0.045739,-0.194819,-0.059170,0.317656,0.013615,-0.513660,-0.150663
icu,-0.337497,-0.231062,1.395516,0.146329,-0.511755,-0.694801,0.652078,-0.239598,-0.134718,0.720945,0.600278,-0.206790
regular,-0.047631,-0.001807,0.234522,0.398583,-0.182207,-0.090626,0.061530,-0.388052,0.194869,-0.269317,0.288441,-0.215770
semi,-0.044747,-0.311876,0.454915,0.483185,-0.614739,-1.037067,2.274914,0.852869,-0.406142,-0.110875,0.993368,0.526006

## Groupings by Labs

There don't seem to be any large groupings of test results in this other category, but there is a chance some of these variables fit in with other lab groupings.

The only grouping I know for sure within the other category is that `Sodium` and `Potassium` levels are tested together.

I want to check the number of missing values for other columns in the dataset to see if some of the columns in other fit in another grouping that we just didn't know to put together. In looking at the missing values for all other variables, I am not seeing any that seem to be in the same grouping as any of the 'other' variables.

In [34]:
pd.set_option('display.max_rows', None)
covid_pos = df[df['SARS-Cov-2 exam result'] == 'positive']
missing_prop = (covid_pos.isnull().sum().sort_values(ascending = False)).to_frame(name = 'num')
missing_prop.reset_index(inplace=True)
missing_prop.rename(columns = {'index':'var'}, inplace = True)
missing_prop['prop'] = missing_prop['num']/len(covid_pos)
missing_prop[(missing_prop['prop'] <= 0.98) & (missing_prop['prop'] > 0)]

                                                  var  num      prop
25                              Urine - Bile pigments  546  0.978495
26                                     Urine - Aspect  546  0.978495
27                                         Urine - pH  546  0.978495
28                                 Urine - Hemoglobin  546  0.978495
29                                 Urine - Leukocytes  546  0.978495
30                                      Urine - Color  546  0.978495
31                                    Urine - Density  546  0.978495
32                               Urine - Urobilinogen  546  0.978495
33                                   Urine - Crystals  546  0.978495
34                            Urine - Red blood cells  546  0.978495
35                         Urine - Granular cylinders  546  0.978495
36                                     Urine - Yeasts  546  0.978495
37                 pCO2 (arterial blood gas analysis)  545  0.976703
38               Hb saturation (arterial blood gases)  545  0.976703
39            Total CO2 (arterial blood gas analysis)  545  0.976703
40          Base excess (arterial blood gas analysis)  545  0.976703
41                 HCO3 (arterial blood gas analysis)  545  0.976703
42                               Arterial Lactic Acid  545  0.976703
43                   pH (arterial blood gas analysis)  545  0.976703
44                  pO2 (arterial blood gas analysis)  545  0.976703
45                 ctO2 (arterial blood gas analysis)  545  0.976703
46                                          Strepto A  544  0.974910
47                      Relationship (Patient/Normal)  543  0.973118
48                   pCO2 (venous blood gas analysis)  538  0.964158
49                   HCO3 (venous blood gas analysis)  538  0.964158
50                     pH (venous blood gas analysis)  538  0.964158
51              Total CO2 (venous blood gas analysis)  538  0.964158
52          Hb saturation (venous blood gas analysis)  538  0.964158
53            Base excess (venous blood gas analysis)  538  0.964158
54                    pO2 (venous blood gas analysis)  538  0.964158
55               International normalized ratio (INR)  535  0.958781
56                      Creatine phosphokinaseÂ (CPK)Â   535  0.958781
57                               Lactic Dehydrogenase  532  0.953405
58                               Alkaline phosphatase  529  0.948029
59                         Gamma-glutamyltransferaseÂ   528  0.946237
60                                      Serum Glucose  525  0.940860
61                             Aspartate transaminase  518  0.928315
62                               Alanine transaminase  518  0.928315
63                                   Direct Bilirubin  518  0.928315
64                                    Total Bilirubin  518  0.928315
65                                 Indirect Bilirubin  518  0.928315
66                                             Sodium  500  0.896057
67                                          Potassium  500  0.896057
68                                               Urea  499  0.894265
69                            Influenza A, rapid test  496  0.888889
70                            Influenza B, rapid test  496  0.888889
71                                         Creatinine  496  0.888889
72                           Proteina C reativa mg/dL  488  0.874552
73                                        Neutrophils  483  0.865591
74                              Mean platelet volume   477  0.854839
75                      Mean corpuscular volume (MCV)  475  0.851254
76                                         Leukocytes  475  0.851254
77                                          Basophils  475  0.851254
78                                          Monocytes  475  0.851254
79            Red blood cell distribution width (RDW)  475  0.851254
80                                        Lymphocytes  475  0.851254
81   Mean corpuscular hemoglobin concentrationÂ (MCHC)  475  0.851254
82                  Mean corpuscular hemoglobin (MCH)  475  0.851254
83                                    Red blood Cells  475  0.851254
84                                          Platelets  475  0.851254
85                                         Hemoglobin  475  0.851254
86                                         Hematocrit  475  0.851254
87                                        Eosinophils  475  0.851254
88                                    Metapneumovirus  446  0.799283
89                               Bordetella pertussis  446  0.799283
90                                    Parainfluenza 2  446  0.799283
91                        Respiratory Syncytial Virus  446  0.799283
92                                        Influenza A  446  0.799283
93                                        Influenza B  446  0.799283
94                                    Parainfluenza 1  446  0.799283
95                                    CoronavirusNL63  446  0.799283
96                             Rhinovirus/Enterovirus  446  0.799283
97                                   Coronavirus HKU1  446  0.799283
98                                    Parainfluenza 3  446  0.799283
99                                         Adenovirus  446  0.799283
100                                   Parainfluenza 4  446  0.799283
101                                   Coronavirus229E  446  0.799283
102                                   CoronavirusOC43  446  0.799283
103                                   Inf A H1N1 2009  446  0.799283
104                          Chlamydophila pneumoniae  446  0.799283

Since `Sodium` and `Potassium` are in a test together, I want to create a binary grouping for the two them.

In [60]:
pd.set_option('display.max_rows', 25)
df['pot_sod_grp'] = np.where((df['Sodium'].notnull()) & (df['Potassium'].notnull()), 1, 0)

In [75]:
df[['pot_sod_grp', 'y']].value_counts()

pot_sod_grp  y
0            discharged    5217
1            discharged     257
             regular         51
             semi            38
0            regular         28
1            icu             21
0            icu             20
             semi            12
dtype: int64

## Imputing Missing Values

For all variables with less than 98% of values missing we will impute them